// <auto-generated/>
#pragma warning disable CS0618
using CPCA.Listmonk.Api.Maintenance.Analytics.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace CPCA.Listmonk.Api.Maintenance.Analytics
{
    /// <summary>
    /// Builds and executes requests for operations under \maintenance\analytics
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class AnalyticsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the CPCA.Listmonk.Api.maintenance.analytics.item collection</summary>
        /// <param name="position">type of GC collected subscribers</param>
        /// <returns>A <see cref="global::CPCA.Listmonk.Api.Maintenance.Analytics.Item.WithTypeItemRequestBuilder"/></returns>
        public global::CPCA.Listmonk.Api.Maintenance.Analytics.Item.WithTypeItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("type", position);
                return new global::CPCA.Listmonk.Api.Maintenance.Analytics.Item.WithTypeItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CPCA.Listmonk.Api.Maintenance.Analytics.AnalyticsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AnalyticsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/maintenance/analytics", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CPCA.Listmonk.Api.Maintenance.Analytics.AnalyticsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public AnalyticsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/maintenance/analytics", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
