// <auto-generated/>
#pragma warning disable CS0618
using CPCA.Listmonk.Api.Dashboard.Charts;
using CPCA.Listmonk.Api.Dashboard.Counts;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace CPCA.Listmonk.Api.Dashboard
{
    /// <summary>
    /// Builds and executes requests for operations under \dashboard
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class DashboardRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The charts property</summary>
        public global::CPCA.Listmonk.Api.Dashboard.Charts.ChartsRequestBuilder Charts
        {
            get => new global::CPCA.Listmonk.Api.Dashboard.Charts.ChartsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The counts property</summary>
        public global::CPCA.Listmonk.Api.Dashboard.Counts.CountsRequestBuilder Counts
        {
            get => new global::CPCA.Listmonk.Api.Dashboard.Counts.CountsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CPCA.Listmonk.Api.Dashboard.DashboardRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DashboardRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/dashboard", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CPCA.Listmonk.Api.Dashboard.DashboardRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public DashboardRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/dashboard", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
