// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace CPCA.Listmonk.Api.Lists
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetOrderQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "ASC")]
        #pragma warning disable CS1591
        ASC,
        #pragma warning restore CS1591
        [EnumMember(Value = "DESC")]
        #pragma warning disable CS1591
        DESC,
        #pragma warning restore CS1591
    }
}
