// <auto-generated/>
#pragma warning disable CS0618
using CPCA.Listmonk.Api.Maintenance.Analytics;
using CPCA.Listmonk.Api.Maintenance.Subscribers;
using CPCA.Listmonk.Api.Maintenance.Subscriptions;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace CPCA.Listmonk.Api.Maintenance
{
    /// <summary>
    /// Builds and executes requests for operations under \maintenance
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class MaintenanceRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The analytics property</summary>
        public global::CPCA.Listmonk.Api.Maintenance.Analytics.AnalyticsRequestBuilder Analytics
        {
            get => new global::CPCA.Listmonk.Api.Maintenance.Analytics.AnalyticsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The subscribers property</summary>
        public global::CPCA.Listmonk.Api.Maintenance.Subscribers.SubscribersRequestBuilder Subscribers
        {
            get => new global::CPCA.Listmonk.Api.Maintenance.Subscribers.SubscribersRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The subscriptions property</summary>
        public global::CPCA.Listmonk.Api.Maintenance.Subscriptions.SubscriptionsRequestBuilder Subscriptions
        {
            get => new global::CPCA.Listmonk.Api.Maintenance.Subscriptions.SubscriptionsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CPCA.Listmonk.Api.Maintenance.MaintenanceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MaintenanceRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/maintenance", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CPCA.Listmonk.Api.Maintenance.MaintenanceRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public MaintenanceRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/maintenance", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
