// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace CPCA.Listmonk.Api.Campaigns.Item.Archive
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ArchivePutRequestBody : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The archive property</summary>
        public bool? Archive { get; set; }
        /// <summary>The archive_meta property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::CPCA.Listmonk.Api.Campaigns.Item.Archive.ArchivePutRequestBody_archive_meta? ArchiveMeta { get; set; }
#nullable restore
#else
        public global::CPCA.Listmonk.Api.Campaigns.Item.Archive.ArchivePutRequestBody_archive_meta ArchiveMeta { get; set; }
#endif
        /// <summary>The archive_template_id property</summary>
        public int? ArchiveTemplateId { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::CPCA.Listmonk.Api.Campaigns.Item.Archive.ArchivePutRequestBody"/> and sets the default values.
        /// </summary>
        public ArchivePutRequestBody()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::CPCA.Listmonk.Api.Campaigns.Item.Archive.ArchivePutRequestBody"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::CPCA.Listmonk.Api.Campaigns.Item.Archive.ArchivePutRequestBody CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::CPCA.Listmonk.Api.Campaigns.Item.Archive.ArchivePutRequestBody();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "archive", n => { Archive = n.GetBoolValue(); } },
                { "archive_meta", n => { ArchiveMeta = n.GetObjectValue<global::CPCA.Listmonk.Api.Campaigns.Item.Archive.ArchivePutRequestBody_archive_meta>(global::CPCA.Listmonk.Api.Campaigns.Item.Archive.ArchivePutRequestBody_archive_meta.CreateFromDiscriminatorValue); } },
                { "archive_template_id", n => { ArchiveTemplateId = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteBoolValue("archive", Archive);
            writer.WriteObjectValue<global::CPCA.Listmonk.Api.Campaigns.Item.Archive.ArchivePutRequestBody_archive_meta>("archive_meta", ArchiveMeta);
            writer.WriteIntValue("archive_template_id", ArchiveTemplateId);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
