// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace CPCA.Listmonk.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum CampaignContentRequest_type
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "regular")]
        #pragma warning disable CS1591
        Regular,
        #pragma warning restore CS1591
        [EnumMember(Value = "optin")]
        #pragma warning disable CS1591
        Optin,
        #pragma warning restore CS1591
    }
}
