// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace CPCA.Listmonk.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class CampaignUpdate : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The altbody property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Altbody { get; set; }
#nullable restore
#else
        public string Altbody { get; set; }
#endif
        /// <summary>The archive property</summary>
        public bool? Archive { get; set; }
        /// <summary>The archive_meta property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::CPCA.Listmonk.Api.Models.CampaignUpdate_archive_meta? ArchiveMeta { get; set; }
#nullable restore
#else
        public global::CPCA.Listmonk.Api.Models.CampaignUpdate_archive_meta ArchiveMeta { get; set; }
#endif
        /// <summary>The archive_template_id property</summary>
        public int? ArchiveTemplateId { get; set; }
        /// <summary>The body property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Body { get; set; }
#nullable restore
#else
        public string Body { get; set; }
#endif
        /// <summary>The content_type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? ContentType { get; set; }
#nullable restore
#else
        public string ContentType { get; set; }
#endif
        /// <summary>The from_email property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? FromEmail { get; set; }
#nullable restore
#else
        public string FromEmail { get; set; }
#endif
        /// <summary>The headers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::CPCA.Listmonk.Api.Models.CampaignUpdate_headers>? Headers { get; set; }
#nullable restore
#else
        public List<global::CPCA.Listmonk.Api.Models.CampaignUpdate_headers> Headers { get; set; }
#endif
        /// <summary>The lists property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<int?>? Lists { get; set; }
#nullable restore
#else
        public List<int?> Lists { get; set; }
#endif
        /// <summary>The messenger property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Messenger { get; set; }
#nullable restore
#else
        public string Messenger { get; set; }
#endif
        /// <summary>The name property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Name { get; set; }
#nullable restore
#else
        public string Name { get; set; }
#endif
        /// <summary>The send_at property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::CPCA.Listmonk.Api.Models.CampaignUpdate_send_at? SendAt { get; set; }
#nullable restore
#else
        public global::CPCA.Listmonk.Api.Models.CampaignUpdate_send_at SendAt { get; set; }
#endif
        /// <summary>The send_later property</summary>
        public bool? SendLater { get; set; }
        /// <summary>The subject property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Subject { get; set; }
#nullable restore
#else
        public string Subject { get; set; }
#endif
        /// <summary>The tags property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Tags { get; set; }
#nullable restore
#else
        public List<string> Tags { get; set; }
#endif
        /// <summary>The template_id property</summary>
        public int? TemplateId { get; set; }
        /// <summary>The type property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Type { get; set; }
#nullable restore
#else
        public string Type { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::CPCA.Listmonk.Api.Models.CampaignUpdate"/> and sets the default values.
        /// </summary>
        public CampaignUpdate()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::CPCA.Listmonk.Api.Models.CampaignUpdate"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::CPCA.Listmonk.Api.Models.CampaignUpdate CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::CPCA.Listmonk.Api.Models.CampaignUpdate();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "altbody", n => { Altbody = n.GetStringValue(); } },
                { "archive", n => { Archive = n.GetBoolValue(); } },
                { "archive_meta", n => { ArchiveMeta = n.GetObjectValue<global::CPCA.Listmonk.Api.Models.CampaignUpdate_archive_meta>(global::CPCA.Listmonk.Api.Models.CampaignUpdate_archive_meta.CreateFromDiscriminatorValue); } },
                { "archive_template_id", n => { ArchiveTemplateId = n.GetIntValue(); } },
                { "body", n => { Body = n.GetStringValue(); } },
                { "content_type", n => { ContentType = n.GetStringValue(); } },
                { "from_email", n => { FromEmail = n.GetStringValue(); } },
                { "headers", n => { Headers = n.GetCollectionOfObjectValues<global::CPCA.Listmonk.Api.Models.CampaignUpdate_headers>(global::CPCA.Listmonk.Api.Models.CampaignUpdate_headers.CreateFromDiscriminatorValue)?.AsList(); } },
                { "lists", n => { Lists = n.GetCollectionOfPrimitiveValues<int?>()?.AsList(); } },
                { "messenger", n => { Messenger = n.GetStringValue(); } },
                { "name", n => { Name = n.GetStringValue(); } },
                { "send_at", n => { SendAt = n.GetObjectValue<global::CPCA.Listmonk.Api.Models.CampaignUpdate_send_at>(global::CPCA.Listmonk.Api.Models.CampaignUpdate_send_at.CreateFromDiscriminatorValue); } },
                { "send_later", n => { SendLater = n.GetBoolValue(); } },
                { "subject", n => { Subject = n.GetStringValue(); } },
                { "tags", n => { Tags = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "template_id", n => { TemplateId = n.GetIntValue(); } },
                { "type", n => { Type = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("altbody", Altbody);
            writer.WriteBoolValue("archive", Archive);
            writer.WriteObjectValue<global::CPCA.Listmonk.Api.Models.CampaignUpdate_archive_meta>("archive_meta", ArchiveMeta);
            writer.WriteIntValue("archive_template_id", ArchiveTemplateId);
            writer.WriteStringValue("body", Body);
            writer.WriteStringValue("content_type", ContentType);
            writer.WriteStringValue("from_email", FromEmail);
            writer.WriteCollectionOfObjectValues<global::CPCA.Listmonk.Api.Models.CampaignUpdate_headers>("headers", Headers);
            writer.WriteCollectionOfPrimitiveValues<int?>("lists", Lists);
            writer.WriteStringValue("messenger", Messenger);
            writer.WriteStringValue("name", Name);
            writer.WriteObjectValue<global::CPCA.Listmonk.Api.Models.CampaignUpdate_send_at>("send_at", SendAt);
            writer.WriteBoolValue("send_later", SendLater);
            writer.WriteStringValue("subject", Subject);
            writer.WriteCollectionOfPrimitiveValues<string>("tags", Tags);
            writer.WriteIntValue("template_id", TemplateId);
            writer.WriteStringValue("type", Type);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
