// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace CPCA.Listmonk.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DashboardCount_data : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The campaigns property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::CPCA.Listmonk.Api.Models.DashboardCount_data_campaigns? Campaigns { get; set; }
#nullable restore
#else
        public global::CPCA.Listmonk.Api.Models.DashboardCount_data_campaigns Campaigns { get; set; }
#endif
        /// <summary>The lists property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::CPCA.Listmonk.Api.Models.DashboardCount_data_lists? Lists { get; set; }
#nullable restore
#else
        public global::CPCA.Listmonk.Api.Models.DashboardCount_data_lists Lists { get; set; }
#endif
        /// <summary>The messages property</summary>
        public int? Messages { get; set; }
        /// <summary>The subscribers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::CPCA.Listmonk.Api.Models.DashboardCount_data_subscribers? Subscribers { get; set; }
#nullable restore
#else
        public global::CPCA.Listmonk.Api.Models.DashboardCount_data_subscribers Subscribers { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::CPCA.Listmonk.Api.Models.DashboardCount_data"/> and sets the default values.
        /// </summary>
        public DashboardCount_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::CPCA.Listmonk.Api.Models.DashboardCount_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::CPCA.Listmonk.Api.Models.DashboardCount_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::CPCA.Listmonk.Api.Models.DashboardCount_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "campaigns", n => { Campaigns = n.GetObjectValue<global::CPCA.Listmonk.Api.Models.DashboardCount_data_campaigns>(global::CPCA.Listmonk.Api.Models.DashboardCount_data_campaigns.CreateFromDiscriminatorValue); } },
                { "lists", n => { Lists = n.GetObjectValue<global::CPCA.Listmonk.Api.Models.DashboardCount_data_lists>(global::CPCA.Listmonk.Api.Models.DashboardCount_data_lists.CreateFromDiscriminatorValue); } },
                { "messages", n => { Messages = n.GetIntValue(); } },
                { "subscribers", n => { Subscribers = n.GetObjectValue<global::CPCA.Listmonk.Api.Models.DashboardCount_data_subscribers>(global::CPCA.Listmonk.Api.Models.DashboardCount_data_subscribers.CreateFromDiscriminatorValue); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::CPCA.Listmonk.Api.Models.DashboardCount_data_campaigns>("campaigns", Campaigns);
            writer.WriteObjectValue<global::CPCA.Listmonk.Api.Models.DashboardCount_data_lists>("lists", Lists);
            writer.WriteIntValue("messages", Messages);
            writer.WriteObjectValue<global::CPCA.Listmonk.Api.Models.DashboardCount_data_subscribers>("subscribers", Subscribers);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
