// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace CPCA.Listmonk.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class DashboardCount_data_subscribers : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The blocklisted property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public global::CPCA.Listmonk.Api.Models.DashboardCount_data_subscribers_blocklisted? Blocklisted { get; set; }
#nullable restore
#else
        public global::CPCA.Listmonk.Api.Models.DashboardCount_data_subscribers_blocklisted Blocklisted { get; set; }
#endif
        /// <summary>The orphans property</summary>
        public int? Orphans { get; set; }
        /// <summary>The total property</summary>
        public int? Total { get; set; }
        /// <summary>
        /// Instantiates a new <see cref="global::CPCA.Listmonk.Api.Models.DashboardCount_data_subscribers"/> and sets the default values.
        /// </summary>
        public DashboardCount_data_subscribers()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::CPCA.Listmonk.Api.Models.DashboardCount_data_subscribers"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::CPCA.Listmonk.Api.Models.DashboardCount_data_subscribers CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::CPCA.Listmonk.Api.Models.DashboardCount_data_subscribers();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "blocklisted", n => { Blocklisted = n.GetObjectValue<global::CPCA.Listmonk.Api.Models.DashboardCount_data_subscribers_blocklisted>(global::CPCA.Listmonk.Api.Models.DashboardCount_data_subscribers_blocklisted.CreateFromDiscriminatorValue); } },
                { "orphans", n => { Orphans = n.GetIntValue(); } },
                { "total", n => { Total = n.GetIntValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteObjectValue<global::CPCA.Listmonk.Api.Models.DashboardCount_data_subscribers_blocklisted>("blocklisted", Blocklisted);
            writer.WriteIntValue("orphans", Orphans);
            writer.WriteIntValue("total", Total);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
