// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace CPCA.Listmonk.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum NewList_optin
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "single")]
        #pragma warning disable CS1591
        Single,
        #pragma warning restore CS1591
        [EnumMember(Value = "double")]
        #pragma warning disable CS1591
        Double,
        #pragma warning restore CS1591
    }
}
