// <auto-generated/>
#pragma warning disable CS0618
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions.Serialization;
using System.Collections.Generic;
using System.IO;
using System;
namespace CPCA.Listmonk.Api.Models
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public partial class ServerConfig_data : IAdditionalDataHolder, IParsable
    #pragma warning restore CS1591
    {
        /// <summary>Stores additional data not described in the OpenAPI description found when deserializing. Can be used for serialization as well.</summary>
        public IDictionary<string, object> AdditionalData { get; set; }
        /// <summary>The lang property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Lang { get; set; }
#nullable restore
#else
        public string Lang { get; set; }
#endif
        /// <summary>The langs property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<global::CPCA.Listmonk.Api.Models.ServerConfig_data_langs>? Langs { get; set; }
#nullable restore
#else
        public List<global::CPCA.Listmonk.Api.Models.ServerConfig_data_langs> Langs { get; set; }
#endif
        /// <summary>The messengers property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public List<string>? Messengers { get; set; }
#nullable restore
#else
        public List<string> Messengers { get; set; }
#endif
        /// <summary>The needs_restart property</summary>
        public bool? NeedsRestart { get; set; }
        /// <summary>The update property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Update { get; set; }
#nullable restore
#else
        public string Update { get; set; }
#endif
        /// <summary>The version property</summary>
#if NETSTANDARD2_1_OR_GREATER || NETCOREAPP3_1_OR_GREATER
#nullable enable
        public string? Version { get; set; }
#nullable restore
#else
        public string Version { get; set; }
#endif
        /// <summary>
        /// Instantiates a new <see cref="global::CPCA.Listmonk.Api.Models.ServerConfig_data"/> and sets the default values.
        /// </summary>
        public ServerConfig_data()
        {
            AdditionalData = new Dictionary<string, object>();
        }
        /// <summary>
        /// Creates a new instance of the appropriate class based on discriminator value
        /// </summary>
        /// <returns>A <see cref="global::CPCA.Listmonk.Api.Models.ServerConfig_data"/></returns>
        /// <param name="parseNode">The parse node to use to read the discriminator value and create the object</param>
        public static global::CPCA.Listmonk.Api.Models.ServerConfig_data CreateFromDiscriminatorValue(IParseNode parseNode)
        {
            _ = parseNode ?? throw new ArgumentNullException(nameof(parseNode));
            return new global::CPCA.Listmonk.Api.Models.ServerConfig_data();
        }
        /// <summary>
        /// The deserialization information for the current model
        /// </summary>
        /// <returns>A IDictionary&lt;string, Action&lt;IParseNode&gt;&gt;</returns>
        public virtual IDictionary<string, Action<IParseNode>> GetFieldDeserializers()
        {
            return new Dictionary<string, Action<IParseNode>>
            {
                { "lang", n => { Lang = n.GetStringValue(); } },
                { "langs", n => { Langs = n.GetCollectionOfObjectValues<global::CPCA.Listmonk.Api.Models.ServerConfig_data_langs>(global::CPCA.Listmonk.Api.Models.ServerConfig_data_langs.CreateFromDiscriminatorValue)?.AsList(); } },
                { "messengers", n => { Messengers = n.GetCollectionOfPrimitiveValues<string>()?.AsList(); } },
                { "needs_restart", n => { NeedsRestart = n.GetBoolValue(); } },
                { "update", n => { Update = n.GetStringValue(); } },
                { "version", n => { Version = n.GetStringValue(); } },
            };
        }
        /// <summary>
        /// Serializes information the current object
        /// </summary>
        /// <param name="writer">Serialization writer to use to serialize this model</param>
        public virtual void Serialize(ISerializationWriter writer)
        {
            _ = writer ?? throw new ArgumentNullException(nameof(writer));
            writer.WriteStringValue("lang", Lang);
            writer.WriteCollectionOfObjectValues<global::CPCA.Listmonk.Api.Models.ServerConfig_data_langs>("langs", Langs);
            writer.WriteCollectionOfPrimitiveValues<string>("messengers", Messengers);
            writer.WriteBoolValue("needs_restart", NeedsRestart);
            writer.WriteStringValue("update", Update);
            writer.WriteStringValue("version", Version);
            writer.WriteAdditionalData(AdditionalData);
        }
    }
}
#pragma warning restore CS0618
