// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace CPCA.Listmonk.Api.Models
{
    /// <summary>Whether to add, remove, or unsubscribe the users.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SubscriberQueryRequest_action
    {
        [EnumMember(Value = "add")]
        #pragma warning disable CS1591
        Add,
        #pragma warning restore CS1591
        [EnumMember(Value = "remove")]
        #pragma warning disable CS1591
        Remove,
        #pragma warning restore CS1591
        [EnumMember(Value = "unsubscribe")]
        #pragma warning disable CS1591
        Unsubscribe,
        #pragma warning restore CS1591
    }
}
