// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace CPCA.Listmonk.Api.Models
{
    /// <summary>confirmed, unconfirmed, or unsubscribed status.</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum SubscriberQueryRequest_status
    {
        [EnumMember(Value = "confirmed")]
        #pragma warning disable CS1591
        Confirmed,
        #pragma warning restore CS1591
        [EnumMember(Value = "unconfirmed")]
        #pragma warning disable CS1591
        Unconfirmed,
        #pragma warning restore CS1591
        [EnumMember(Value = "unsubscribed")]
        #pragma warning disable CS1591
        Unsubscribed,
        #pragma warning restore CS1591
    }
}
