// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace CPCA.Listmonk.Api.Models
{
    /// <summary>Type of the template</summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public enum UpdateTemplate_type
    {
        [EnumMember(Value = "campaign")]
        #pragma warning disable CS1591
        Campaign,
        #pragma warning restore CS1591
        [EnumMember(Value = "campaign_visual")]
        #pragma warning disable CS1591
        Campaign_visual,
        #pragma warning restore CS1591
        [EnumMember(Value = "tx")]
        #pragma warning disable CS1591
        Tx,
        #pragma warning restore CS1591
    }
}
