// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace CPCA.Listmonk.Api.Campaigns.Item.Status
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum StatusPutRequestBody_status
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "scheduled")]
        #pragma warning disable CS1591
        Scheduled,
        #pragma warning restore CS1591
        [EnumMember(Value = "running")]
        #pragma warning disable CS1591
        Running,
        #pragma warning restore CS1591
        [EnumMember(Value = "paused")]
        #pragma warning disable CS1591
        Paused,
        #pragma warning restore CS1591
        [EnumMember(Value = "cancelled")]
        #pragma warning disable CS1591
        Cancelled,
        #pragma warning restore CS1591
    }
}
