// <auto-generated/>
#pragma warning disable CS0618
using CPCA.Listmonk.Api.Subscribers.Query.Blocklist;
using CPCA.Listmonk.Api.Subscribers.Query.Delete;
using CPCA.Listmonk.Api.Subscribers.Query.Lists;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace CPCA.Listmonk.Api.Subscribers.Query
{
    /// <summary>
    /// Builds and executes requests for operations under \subscribers\query
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class QueryRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The blocklist property</summary>
        public global::CPCA.Listmonk.Api.Subscribers.Query.Blocklist.BlocklistRequestBuilder Blocklist
        {
            get => new global::CPCA.Listmonk.Api.Subscribers.Query.Blocklist.BlocklistRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The deletePath property</summary>
        public global::CPCA.Listmonk.Api.Subscribers.Query.Delete.DeleteRequestBuilder DeletePath
        {
            get => new global::CPCA.Listmonk.Api.Subscribers.Query.Delete.DeleteRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The lists property</summary>
        public global::CPCA.Listmonk.Api.Subscribers.Query.Lists.ListsRequestBuilder Lists
        {
            get => new global::CPCA.Listmonk.Api.Subscribers.Query.Lists.ListsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CPCA.Listmonk.Api.Subscribers.Query.QueryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public QueryRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/subscribers/query", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CPCA.Listmonk.Api.Subscribers.Query.QueryRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public QueryRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/subscribers/query", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
