// <auto-generated/>
#pragma warning disable CS0618
using CPCA.Listmonk.Api.Maintenance.Subscriptions.Unconfirmed;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace CPCA.Listmonk.Api.Maintenance.Subscriptions
{
    /// <summary>
    /// Builds and executes requests for operations under \maintenance\subscriptions
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SubscriptionsRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The unconfirmed property</summary>
        public global::CPCA.Listmonk.Api.Maintenance.Subscriptions.Unconfirmed.UnconfirmedRequestBuilder Unconfirmed
        {
            get => new global::CPCA.Listmonk.Api.Maintenance.Subscriptions.Unconfirmed.UnconfirmedRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CPCA.Listmonk.Api.Maintenance.Subscriptions.SubscriptionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SubscriptionsRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/maintenance/subscriptions", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CPCA.Listmonk.Api.Maintenance.Subscriptions.SubscriptionsRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SubscriptionsRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/maintenance/subscriptions", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
