// <auto-generated/>
#pragma warning disable CS0618
using CPCA.Listmonk.Api.Public.Lists;
using CPCA.Listmonk.Api.Public.Subscription;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace CPCA.Listmonk.Api.Public
{
    /// <summary>
    /// Builds and executes requests for operations under \public
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class PublicRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The lists property</summary>
        public global::CPCA.Listmonk.Api.Public.Lists.ListsRequestBuilder Lists
        {
            get => new global::CPCA.Listmonk.Api.Public.Lists.ListsRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>The subscription property</summary>
        public global::CPCA.Listmonk.Api.Public.Subscription.SubscriptionRequestBuilder Subscription
        {
            get => new global::CPCA.Listmonk.Api.Public.Subscription.SubscriptionRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CPCA.Listmonk.Api.Public.PublicRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PublicRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/public", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CPCA.Listmonk.Api.Public.PublicRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public PublicRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/public", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
