// <auto-generated/>
#pragma warning disable CS0618
using CPCA.Listmonk.Api.Settings.Smtp.Test;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace CPCA.Listmonk.Api.Settings.Smtp
{
    /// <summary>
    /// Builds and executes requests for operations under \settings\smtp
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class SmtpRequestBuilder : BaseRequestBuilder
    {
        /// <summary>The test property</summary>
        public global::CPCA.Listmonk.Api.Settings.Smtp.Test.TestRequestBuilder Test
        {
            get => new global::CPCA.Listmonk.Api.Settings.Smtp.Test.TestRequestBuilder(PathParameters, RequestAdapter);
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CPCA.Listmonk.Api.Settings.Smtp.SmtpRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SmtpRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/settings/smtp", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CPCA.Listmonk.Api.Settings.Smtp.SmtpRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public SmtpRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/settings/smtp", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
