// <auto-generated/>
#pragma warning disable CS0618
using CPCA.Listmonk.Api.Lang.Item;
using Microsoft.Kiota.Abstractions.Extensions;
using Microsoft.Kiota.Abstractions;
using System.Collections.Generic;
using System.IO;
using System.Threading.Tasks;
using System;
namespace CPCA.Listmonk.Api.Lang
{
    /// <summary>
    /// Builds and executes requests for operations under \lang
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    public partial class LangRequestBuilder : BaseRequestBuilder
    {
        /// <summary>Gets an item from the CPCA.Listmonk.Api.lang.item collection</summary>
        /// <param name="position">JSON language pack required</param>
        /// <returns>A <see cref="global::CPCA.Listmonk.Api.Lang.Item.WithLangItemRequestBuilder"/></returns>
        public global::CPCA.Listmonk.Api.Lang.Item.WithLangItemRequestBuilder this[string position]
        {
            get
            {
                var urlTplParams = new Dictionary<string, object>(PathParameters);
                urlTplParams.Add("lang", position);
                return new global::CPCA.Listmonk.Api.Lang.Item.WithLangItemRequestBuilder(urlTplParams, RequestAdapter);
            }
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CPCA.Listmonk.Api.Lang.LangRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="pathParameters">Path parameters for the request</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LangRequestBuilder(Dictionary<string, object> pathParameters, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/lang", pathParameters)
        {
        }
        /// <summary>
        /// Instantiates a new <see cref="global::CPCA.Listmonk.Api.Lang.LangRequestBuilder"/> and sets the default values.
        /// </summary>
        /// <param name="rawUrl">The raw URL to use for the request builder.</param>
        /// <param name="requestAdapter">The request adapter to use to execute the requests.</param>
        public LangRequestBuilder(string rawUrl, IRequestAdapter requestAdapter) : base(requestAdapter, "{+baseurl}/lang", rawUrl)
        {
        }
    }
}
#pragma warning restore CS0618
