// <auto-generated/>
using System.Runtime.Serialization;
using System;
namespace CPCA.Listmonk.Api.Bounces
{
    [global::System.CodeDom.Compiler.GeneratedCode("Kiota", "1.0.0")]
    #pragma warning disable CS1591
    public enum GetOrder_byQueryParameterType
    #pragma warning restore CS1591
    {
        [EnumMember(Value = "email")]
        #pragma warning disable CS1591
        Email,
        #pragma warning restore CS1591
        [EnumMember(Value = "campaign_name")]
        #pragma warning disable CS1591
        Campaign_name,
        #pragma warning restore CS1591
        [EnumMember(Value = "source")]
        #pragma warning disable CS1591
        Source,
        #pragma warning restore CS1591
        [EnumMember(Value = "created_at")]
        #pragma warning disable CS1591
        Created_at,
        #pragma warning restore CS1591
    }
}
